//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_crud
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Modelo { get; set; }
        public Nullable<short> Ano { get; set; }
        public Nullable<short> Fabricacao { get; set; }
        public string Cor { get; set; }
        public Nullable<byte> Combustivel { get; set; }
        public Nullable<bool> Automatico { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public bool Ativo { get; set; }
    }
}
